using GitGab.Models.Config;
using GitGab.Models.Connector;

namespace GitGab.Services.Connector.Providers;

public class ConsoleConnector : IConnector
{
    private readonly ConsoleConnectorConfig _config;

    public string Name => _config.Name;

    public ConsoleConnector(ConsoleConnectorConfig config)
    {
        _config = config;
    }

    public Task<ConnectorResult> SendAsync(ConnectorMessage message, CancellationToken ct = default)
    {
        Console.WriteLine("=== GitGab Summary ===");
        Console.WriteLine();
        Console.WriteLine(message.Summary);
        Console.WriteLine();
        Console.WriteLine("Generated by GitGab with " + message.LLMModel);
        
        return Task.FromResult(new ConnectorResult
        {
            ConnectorName = Name,
            Success = true,
            SentAt = DateTimeOffset.UtcNow
        });
    }
}
