using GitGab.Models.Config;
using GitGab.Models.Connector;
using MailKit.Net.Smtp;
using MimeKit;

namespace GitGab.Services.Connector.Providers;

public class EmailConnector : IConnector
{
    private readonly EmailConnectorConfig _config;

    public string Name => _config.Name;

    public EmailConnector(EmailConnectorConfig config)
    {
        _config = config;
    }

    public async Task<ConnectorResult> SendAsync(ConnectorMessage message, CancellationToken ct = default)
    {
        try
        {
            var emailMessage = new MimeMessage();
            emailMessage.From.Add(new MailboxAddress("GitGab", _config.From));

            foreach (var to in _config.To)
            {
                emailMessage.To.Add(MailboxAddress.Parse(to));
            }

            var subject = _config.Subject
                .Replace("{{repo.name}}", message.RepositoryName)
                .Replace("{{date}}", DateTimeOffset.UtcNow.ToString("yyyy-MM-dd"));
            emailMessage.Subject = subject;

            var bodyBuilder = new BodyBuilder();
            if (_config.IsHtml)
            {
                bodyBuilder.HtmlBody = FormatAsHtml(message);
            }
            else
            {
                bodyBuilder.TextBody = message.Summary;
            }
            emailMessage.Body = bodyBuilder.ToMessageBody();

            using var client = new SmtpClient();
            await client.ConnectAsync(_config.Smtp.Host, _config.Smtp.Port, _config.Smtp.UseSsl, ct);

            if (!string.IsNullOrEmpty(_config.Smtp.Username) && !string.IsNullOrEmpty(_config.Smtp.Password))
            {
                await client.AuthenticateAsync(_config.Smtp.Username, _config.Smtp.Password, ct);
            }

            await client.SendAsync(emailMessage, ct);
            await client.DisconnectAsync(true, ct);

            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = true,
                SentAt = DateTimeOffset.UtcNow
            };
        }
        catch (Exception ex)
        {
            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = false,
                ErrorMessage = ex.Message,
                SentAt = DateTimeOffset.UtcNow
            };
        }
    }

    private string FormatAsHtml(ConnectorMessage message)
    {
        var html = "<html><body>";
        html += "<h1>GitGab Summary: " + System.Web.HttpUtility.HtmlEncode(message.RepositoryName) + "</h1>";
        html += "<p><strong>Generated:</strong> " + message.GeneratedAt.ToString("yyyy-MM-dd HH:mm") + "</p>";
        html += "<hr />";
        html += "<div>" + message.Summary.Replace("\n", "<br />") + "</div>";
        html += "<hr />";
        html += "<p><em>Generated by GitGab with " + message.LLMModel + "</em></p>";
        html += "</body></html>";
        return html;
    }
}
