using GitGab.Models.Config;
using GitGab.Models.Connector;

namespace GitGab.Services.Connector.Providers;

public class FileConnector : IConnector
{
    private readonly FileConnectorConfig _config;

    public string Name => _config.Name;

    public FileConnector(FileConnectorConfig config)
    {
        _config = config;
    }

    public async Task<ConnectorResult> SendAsync(ConnectorMessage message, CancellationToken ct = default)
    {
        try
        {
            // Replace placeholders in path
            var path = _config.Path
                .Replace("{{repo.name}}", message.RepositoryName)
                .Replace("{{date}}", DateTimeOffset.UtcNow.ToString("yyyy-MM-dd"));

            // Ensure directory exists
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var content = _config.Format.ToLower() switch
            {
                "json" => SerializeToJson(message),
                "html" => FormatAsHtml(message),
                _ => message.Summary // markdown or text
            };

            await File.WriteAllTextAsync(path, content, ct);

            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = true,
                SentAt = DateTimeOffset.UtcNow
            };
        }
        catch (Exception ex)
        {
            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = false,
                ErrorMessage = ex.Message,
                SentAt = DateTimeOffset.UtcNow
            };
        }
    }

    private string SerializeToJson(ConnectorMessage message)
    {
        return System.Text.Json.JsonSerializer.Serialize(message, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
    }

    private string FormatAsHtml(ConnectorMessage message)
    {
        var html = "<html><body>";
        html += "<h1>GitGab Summary: " + message.RepositoryName + "</h1>";
        html += "<pre>" + System.Web.HttpUtility.HtmlEncode(message.Summary) + "</pre>";
        html += "<p><em>Generated by GitGab with " + message.LLMModel + "</em></p>";
        html += "</body></html>";
        return html;
    }
}
