using GitGab.Models.Config;
using GitGab.Models.Connector;
using System.Text;
using System.Text.Json;

namespace GitGab.Services.Connector.Providers;

public class SlackConnector : IConnector
{
    private readonly SlackConnectorConfig _config;
    private readonly IHttpClientFactory _httpClientFactory;

    public string Name => _config.Name;

    public SlackConnector(SlackConnectorConfig config, IHttpClientFactory httpClientFactory)
    {
        _config = config;
        _httpClientFactory = httpClientFactory;
    }

    public async Task<ConnectorResult> SendAsync(ConnectorMessage message, CancellationToken ct = default)
    {
        try
        {
            var webhookUrl = _config.WebhookUrl;
            if (string.IsNullOrEmpty(webhookUrl))
            {
                return new ConnectorResult
                {
                    ConnectorName = Name,
                    Success = false,
                    ErrorMessage = "Slack webhook URL is not configured",
                    SentAt = DateTimeOffset.UtcNow
                };
            }

            // Format message for Slack
            var slackMessage = new
            {
                text = "GitGab Weekly Summary",
                blocks = new object[]
                {
                    new
                    {
                        type = "header",
                        text = new
                        {
                            type = "plain_text",
                            text = ":robot_face: GitGab Summary :robot_face:",
                            emoji = true
                        }
                    },
                    new
                    {
                        type = "section",
                        text = new
                        {
                            type = "mrkdwn",
                            text = "*Repository:* `" + message.RepositoryName + "`\n*Generated:* " + message.GeneratedAt.ToString("yyyy-MM-dd HH:mm")
                        }
                    },
                    new
                    {
                        type = "divider"
                    },
                    new
                    {
                        type = "section",
                        text = new
                        {
                            type = "mrkdwn",
                            text = message.Summary
                        }
                    },
                    new
                    {
                        type = "context",
                        elements = new object[]
                        {
                            new
                            {
                                type = "mrkdwn",
                                text = "Generated by GitGab with " + message.LLMModel
                            }
                        }
                    }
                }
            };

            var json = JsonSerializer.Serialize(slackMessage);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var httpClient = _httpClientFactory.CreateClient("GitGabHttpClient");
            var response = await httpClient.PostAsync(webhookUrl, content, ct);
            response.EnsureSuccessStatusCode();

            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = true,
                SentAt = DateTimeOffset.UtcNow
            };
        }
        catch (Exception ex)
        {
            return new ConnectorResult
            {
                ConnectorName = Name,
                Success = false,
                ErrorMessage = ex.Message,
                SentAt = DateTimeOffset.UtcNow
            };
        }
    }
}
